import { ROUTER } from '@/common/constants'
import { TAppPropsWithLayout } from '@/common/types'
import BasicLayout from '@/layouts/BasicLayout'
import MainLayout from '@/layouts/MainLayout'
import { checkMatchesRoute, handleLocalStorage } from '@/utils'
import { useRouter } from 'next/router'
import '@/styles/globals.scss'
import { useState } from 'react'
import { ThemeProvider } from '@mui/material'
import { mainTheme } from '@/utils/theme'
import Head from 'next/head'
import Loading from '@/components/atoms/Loading'
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify'

const App = ({ Component, pageProps }: TAppPropsWithLayout) => {
  const getLayout = Component.getLayout || ((page) => page)
  const router = useRouter()
  const [loading, setLoading] = useState(false)
  const isAuthPage = checkMatchesRoute(router, ROUTER.AUTH)

  const Layout = () => {
    return isAuthPage ? (
      <BasicLayout>{getLayout(<Component {...pageProps} />)}</BasicLayout>
    ) : (
      <MainLayout>{getLayout(<Component {...pageProps} />)}</MainLayout>
    )
  }

  return (
    <ThemeProvider theme={mainTheme}>
      <main>
        <Head>
          <title>Vocabu</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
          <link rel='preconnect' href='https://fonts.googleapis.com' />
          <link rel='preconnect' href='https://fonts.gstatic.com' />
          {/* <link href='https://fonts.googleapis.com/css2?family=Public+Sans&display=swap' rel='stylesheet' /> */}
        </Head>
        <Loading loading={loading} setLoading={setLoading} />
        <Layout />
        <ToastContainer />
      </main>
    </ThemeProvider>
  )
}

export default App
