import Head from 'next/head'

const Home = () => {
  return (
    <>
      <Head>
        <title>NextApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  )
}

export default Home
